/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creatingdatabean;

/**
 *
 * @author as5373u
 */
public class timeBeans extends javax.swing.JPanel {

    /**
     * Creates new form timeBeans
     */
    public timeBeans() {
        initComponents();
    }
    
    public String getHour() {
        return hours.getText();
    }

    public void setHour(String hh) {
        hours.setText(hh);
    }
    
    public String getMinute() {
        return minutes.getText();
    }

    public void setMinute(String mm) {
        minutes.setText(mm);
    }
    
    public String getSecond() {
        return seconds.getText();
    }

    public void setSecond(String ss) {
        seconds.setText(ss);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hours = new javax.swing.JLabel();
        seconds = new javax.swing.JLabel();
        minutes = new javax.swing.JLabel();

        hours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hours.setText("hh");
        hours.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        seconds.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seconds.setText("ss");
        seconds.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        minutes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minutes.setText("mm");
        minutes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hours)
                .addGap(5, 5, 5)
                .addComponent(minutes)
                .addGap(5, 5, 5)
                .addComponent(seconds)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hours)
                    .addComponent(minutes)
                    .addComponent(seconds))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hours;
    private javax.swing.JLabel minutes;
    private javax.swing.JLabel seconds;
    // End of variables declaration//GEN-END:variables
}
