/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Time;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author as5373u
 */
public class TimeKeeping extends javax.swing.JFrame {

    int run = 0;

    public TimeKeeping() {
        initComponents();
        Date dateNow1 = new Date();
        SimpleDateFormat sdf1 = new SimpleDateFormat("EEEE"); //Shows the day
        day.setText(sdf1.format(dateNow1));        
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yyyy"); //Show the day/month/year
        date.setText(sdf2.format(dateNow1));
        new Thread() {
            @Override
            public void run() {
                while (run == 0) {
                    Date dateNow = new Date();
                    SimpleDateFormat sdf1 = new SimpleDateFormat("kk:mm:ss aaaa"); // Shows the time
                    currentTime.setText(sdf1.format(dateNow));
                    try{
                        Thread.sleep(500);
                    }catch (InterruptedException e){
                        System.out.println("Problem: " + e);
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        currentTime = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(340, 900));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentTime.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        currentTime.setForeground(new java.awt.Color(0, 255, 102));
        currentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(currentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 270, 70));

        day.setBackground(new java.awt.Color(0, 0, 0));
        day.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        day.setForeground(new java.awt.Color(0, 255, 153));
        day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 30));

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setForeground(new java.awt.Color(0, 204, 204));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(721, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeKeeping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeKeeping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentTime;
    private javax.swing.JLabel date;
    private javax.swing.JLabel day;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
