/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package date;

/**
 *
 * @author as5373u
 */
public class DateBean extends javax.swing.JPanel {

    /**
     * Creates new form DateBean
     */
    public DateBean() {
        initComponents();
    }
    
    public String getDay() {
        return Day.getText();
    }

    public void setDay(String dd) {
        Day.setText(dd);
    }
    
    public String getMonth() {
        return Month.getText();
    }

    public void setMonth(String mm) {
        Month.setText(mm);
    }
    
    public String getYear() {
        return Year.getText();
    }

    public void setYear(String yyyy) {
        Year.setText(yyyy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Day = new javax.swing.JLabel();
        Month = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();

        Day.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Day.setText("dd");
        Day.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Month.setText("mm");
        Month.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Year.setText("yyyy");
        Year.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Day)
                .addGap(5, 5, 5)
                .addComponent(Month)
                .addGap(5, 5, 5)
                .addComponent(Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Day)
                    .addComponent(Month)
                    .addComponent(Year))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Day;
    private javax.swing.JLabel Month;
    private javax.swing.JLabel Year;
    // End of variables declaration//GEN-END:variables
}
